### ISSUE TITLE
nb br not working

### ISSUE THREAD

**Issue by eshad** [xwmx/nb#112]
web not working in my platform 
can you please point the change for termux

nb br + nb br -g both are not working

**Comment by xwmx** [comment]
`nb browse` depends on [`ncat`](https://nmap.org/ncat/), which is available as part of the `nmap` package in most package managers, and [`pandoc`](https://pandoc.org/), so make sure both are installed. Here's the list of recommended packages from Ubuntu, which might be available under the same names for Termux:

```text
bash-completion
bat
curl
ncat
pandoc
python3-pygments
ripgrep
tig
w3m
```

Let me know if this helps.

**Comment by voxelv** [comment]
I have both `nmap` and `pandoc` installed (as well as all the other recommended dependencies) and have checked that they respond with reasonable output when run independently of `nb`. (e.g. `ncat --help`, `w3m google.com`).

However, `nb browse` isn't working for me. I just get a blank page. `nb b -g` also doesn't work, and shows this output:
```
> nb b -g
Listening: http://localhost:6789
```
it immediately returns, without opening any gui, and the return-code is `1`

**Comment by xwmx** [comment]
@voxelv Thanks for the information. Can you try the following two commands and let me know if there is any output? It should print the web page markup to the terminal. The first command uses the server and the second one bypasses the server.

```bash
nb browse --print
```
```bash
nb browse --print-container
```

**Comment by voxelv** [comment]
`nb browse --print` seems to hang (cursor is blinking, but no output).

`nb browse --print-container` shows a big html output with `<title>nb browse home:</title>`

**Comment by xwmx** [comment]
@voxelv Thanks. Can you try running the following command, then opening http://localhost:6789/ in a GUI web browser? The command should stay open listening for a request and then exit after serving the page to the browser:

```bash
ncat --exec "nb browse --respond" --listen "localhost" "6789"
```

**Comment by voxelv** [comment]
That command exits pretty quickly (1 to 2 seconds after running), with exit code `2`. Trying to go to that address times out.

I'm a software dev, but not as familiar with Javascript/HTML/webservers. I'd be happy to help debug if there's anything I can do.

I will mention that `nb browse` works fine on my Arch box, so it might be a Windows vs. `ncat` issue. I installed
"Latest stable release self-installer: [nmap-7.94-setup.exe](https://nmap.org/dist/nmap-7.94-setup.exe)"
from [Nmap](https://nmap.org/download.html#windows).

**Comment by voxelv** [comment]
@eshad What is the issue with path? How can I fix it? `ncat` is installed with Nmap:
```
> which ncat
/c/Program Files (x86)/Nmap/ncat
```

**Comment by xwmx** [comment]
@voxelv The issue that @eshad encountered was different.

@voxelv It looks like the error has something to do with `ncat` and Windows. I would have to run commands and experiment in order to determine what’s not working. There are alternatives to `ncat` that could be used in `nb` for handling the connection, including `socat`, `nc`, `accept` in Bash 5.2+. I haven’t gotten any of them to work cross platform yet. For example, `nc` on macOS doesn’t include the `-e` / `—exec` option, and I haven’t gotten workarounds to work yet. I’ll have to look into this more.

**Comment by xwmx** [comment]
@voxelv I was able to implement the server in both `nc` / `netcat` as well as pure Bash 5.2 `accept`. 😄 This is available in the latest version in the repository. If you are able to run the latest repo version, please try it and let me know if it works. It should skip `ncat` on Windows and automatically use the Bash 5.2 `accept` implementation. You can also force it to use `accept` by calling `nb` with `accept` or `bash` assigned to the `$NB_BROWSE_SERVER_TOOL` variable, e.g.:

```bash
NB_BROWSE_SERVER_TOOL="accept" nb b -s
```

**Comment by voxelv** [comment]
I forgot to use that variable, so once I ran `NB_BROWSE_SERVER_TOOL="accept" nb b -s` I got the following:
```
$ NB_BROWSE_SERVER_TOOL="accept" nb b -s
/usr/bin/nb: line 21724: ACCEPT_FD: unbound variable
/usr/bin/nb: line 21726: ACCEPT_FD: ambiguous redirect
/usr/bin/nb: line 21724: ACCEPT_FD: unbound variable
/usr/bin/nb: line 21726: ACCEPT_FD: ambiguous redirect
Listening: http://localhost:6789
/usr/bin/nb: line 21724: ACCEPT_FD: unbound variable
/usr/bin/nb: line 21726: ACCEPT_FD: ambiguous redirect
Press any key to exit.../usr/bin/nb: line 21724: ACCEPT_FD: unbound variable
/usr/bin/nb: line 21726: ACCEPT_FD: ambiguous redirect
/usr/bin/nb: line 21724: ACCEPT_FD: unbound variable
/usr/bin/nb: line 21726: ACCEPT_FD: ambiguous redirect
/usr/bin/nb: line 21724: ACCEPT_FD: unbound variable
/usr/bin/nb: line 21726: ACCEPT_FD: ambiguous redirect
/usr/bin/nb: line 21724: ACCEPT_FD: unbound variable
...
```
with those last two lines repeating spamming

**Comment by xwmx** [comment]
@voxelv Thanks. It looks like [`accept`](https://git.savannah.gnu.org/cgit/bash.git/tree/examples/loadables/accept.c) is loading but the `$ACCEPT_FD` file descriptor is not getting set, which might have something to do with Windows.

I'll probably revert this to using `ncat` on Windows even though that doesn't currently work, either. `ncat` is the best tool for this so far on other platforms since it handles concurrent requests, which is required for the Ace editor to load fully since it requests multiple JavaScript files.

Two other implementations that we could try are with `socat` or with `python`.

**Comment by eshad** [comment]
By the way I was using the termux terminal and issue was solved haha. 
Thanks you all guys...
