### ISSUE TITLE
Git sync did not work initially with`nb remote set` 

### ISSUE THREAD

**Issue by niranjans** [xwmx/nb#18]
The CLI kept saying notes synced even though the notes were not showing up on Github. 

Eventually, I realized I had to do `git push --set-upstream origin master` in the notebook folder since it was a new repo. 

Perhaps this should be mentioned in the ReadMe? Or can this be handled through `nb` itself?

**Comment by dj-bauer** [comment]
Don't you use `nb init` for that?

**Comment by niranjans** [comment]
Ahh I see. I was just following the ReadMe and I believe `nb init` is not mentioned in the Git sync section so I got confused.

**Comment by RogerTouchCR** [comment]
I was also having an issue with this. From the default setup and notebook, adding the remote did not work out of the box.
Since the default set includes the notebook stored in the home directory, I didn't use `nb init`.

I ran `nb remote set https://url-to-get.github.com/that-repo.git` which successfully added the remote. However nothing was syncing.

Running `nb sync` even produced output that said it synced properly with it not actually syncing.

To correctly get the default notebook to sync, I ran `nb git push --set-upstream origin master` and now the background sync is happening as it should.

Hope this helps!

**Comment by SantaRoger** [comment]
I was also having an issue with this. From the default setup and notebook, adding the remote did not work out of the box.
Since the default set includes the notebook stored in the home directory, I didn't use nb init.

I ran nb remote set https://url-to-get.github.com/that-repo.git which successfully added the remote. However nothing was syncing.

Running nb sync even produced output that said it synced properly with it not actually syncing.

To correctly get the default notebook to sync, I ran nb git push --set-upstream origin master and now the background sync is happening as it should.

Hope this helps!
