### ISSUE TITLE
nb crashed and it does not open anymore

### ISSUE THREAD

**Issue by ouyama-sa** [xwmx/nb#292]
Problem: nb is not starting.
I was trying to rename a todo entry with the --to-title option, when it crashed completely and closed. After that the nb command does not work, neither with options such as --show. 
I tried to reboot the terminal and even the whole DE with no success. 

I am sorry for not providing more information, I am not familiarized with the program yet.

**Comment by ouyama-sa** [comment]
### Additional information:

I was able to reproduce the crash:

_(on a new notebook)_

1. `nb todo add "todo1"`
2. `nb rename 1 --to-title`
3. `nb duplicate 1`
4. change the name of the duplicated todo
5. `nb rename 2 --to-title`
6. output:   "! Move index update failed."

The crash happens after this. 

Solution: cd into .nb and manually delete the notebook folder.

Again, I am sorry if this is a major error on my part, I am still learning to use this program and I have not seen anything on the documentation about this. 


[PRINTS OF THE PROCEDURE]

![image](https://github.com/xwmx/nb/assets/127455926/f101adb3-a1e5-461c-8927-85de55a3ef9c)
![image](https://github.com/xwmx/nb/assets/127455926/53df6329-e84e-4872-81fb-2ae1e688f83d)

**Comment by xwmx** [comment]
@ouyama-sa Thanks for the detailed information. It looks like this was due to an issue with bracket handling when updating the index. This should be fixed as of version 7.9.0. If it still isn’t functioning, you can try running `nb index reconcile` and see if it fixes the index. Let me know if you run into any more issues with this. Thanks!
