### ISSUE TITLE
`nb list` with `-p` option doesn't have the header and footer

### ISSUE THREAD

**Issue by foozzi** [xwmx/nb#312]
For example:
`nb 01-zettel: ls -p 1` doesn't include the header and footer

**Comment by xwmx** [comment]
@foozzi This is actually by design. `nb` and `nb ls` display the header and footer, while `nb list` just displays the list. `nb` and `nb ls` omit the header and footer when used with filtering and sorting options such as `-p <page>`, `-r`, `-s`, `--<type>`, and filter keywords. This makes it easier to identify that it's a modified display of the list.

Let me know if I missed something or if I can clarify anything else.
