### ISSUE TITLE
Please allow user to choose their html viewer tool

### ISSUE THREAD

**Issue by vkuznet** [xwmx/nb#36]
HI,
I found that nb has hardcoded order of tools to view html content where w3m is a first choice. I bet that users have different preferences and in my case lynx is my first choice. I would suggest to allow user to choose their favorite tool through configuration, like NB_PEEK_TOOL or NB_PREVIEW_TOOL. Moreover, for some of us we may configure it with specific options.

**Comment by xwmx** [comment]
Thanks for the suggestion!

I looked into it a bit and it appears to best first step is to respect the user's `$BROWSER` environment variable. This variable is not standard, but it is included in the [Debian](https://unix.stackexchange.com/questions/213367/where-do-editor-pager-browser-environment-variables-come-from) and [Arch](https://wiki.archlinux.org/index.php/environment_variables) documentation. `nb` should work when this is set to a browser command with or without options. `nb` does not support more complex `$BROWSER` values, like a "colon-delimited list of  commands" mentioned in the Debian documentation.

So as of version 5.6.1, `nb` now checks the environment for a `$BROWSER` environment variable and uses the specified browser instead of always defaulting to `w3m`.  Currently it only fully supports `w3m` and `lynx`. If `$BROWSER` is not set, it falls back to `w3m` and then `lynx`.

`w3m` is still used to escape HTML entities from titles and descriptions when saving a bookmark. When `w3m` is not available, the title and description are saved without escaping HTML entities. I feel that this is OK given that `w3m` is a recommended dependency, the only platform I'm aware of that `w3m` doesn't work on is WSL 1, and adding `lynx` support for that particular operation doesn't seem critical. I added `TODO` comments indicating these operations should become browser-agnostic when time permits.

A setting has not yet been added within `nb` for the browser. I'd like to see how it goes just respecting the `$BROWSER` environment variable. I'm trying to avoid adding too many lines to `nb` and want to see what other settings might need to be added.

I'm going to close this as complete. If you have any feedback, please let me know.

I hope this helps!

**Comment by weierophinney** [comment]
Leaving a note here in case anybody else comes across a similar issue I encountered.

I use ubuntu, and `$BROWSER` is set to `/usr/bin/x-www-browser`, which eventually resolves to the browser alternative you have set, which is generally your GUI browser. I wanted to instead use w3m by default so that I stay in the CLI. As such, I wrote the following function in my shell configuration:

```bash
nb () {
    BROWSER=w3m nb "$@"
}
```

This works great. However...

Occasionally when in w3m, I want to open a link or the current page in my GUI browser (for example, if I have a link to an external site). w3m has command bindings for this (`Esc M` and `M`, respectively), and you can configure which browser to open (defaults to `/usr/bin/sensible-browser`, which, again, eventually resolves to the GUI browser).

The problem? sensible-browser uses the `$BROWSER` value, which means everything opens in w3m.

I found two ways to fix this:

- When in w3m, press "o" to open the options screen. Find the External browser setting, and set it to the specific binary of the browser you use.
- Since the above means that if you switch your default browser, w3m will still be opening your previous, the better way is to just clear the `$BROWSER` value when opening nb:
  ```bash
  nb () {
      BROWSER= nb "$@"
  }
  ```

This latter works perfectly, and is future-proof with any changes in your default browser.

**Comment by xwmx** [comment]
@weierophinney Thanks for the information! Your comment prompted me to add a `$NB_BROWSER` variable that can be set instead of `$BROWSER`, in case that's helpful.

**Comment by weierophinney** [comment]
Works brilliantly! I've set `NB_BROWSER` in my shell configuration, and now can remove the `nb()` function definition entirely!

Thanks, @xwmx !
