### ISSUE TITLE
Handle ctrl+d as an EOF signal

### ISSUE THREAD

**Issue by RoToRx88** [xwmx/nb#40]
Similarly to bash, it would be nice to have the `nb shell` handle `ctrl+d` like bash does.
I've built up such muscle memory that when I try to leave the `nb shell` I always do `ctrl+d` at least 5/6 times before remembering that it's `ctrl+c` that closes the shell. (BTW for my personal culture, why did you choose `ctrl+c` and not `ctrl+d` ?)

Anyway thanks for this great tool ! Keep up ! :)

**Comment by xwmx** [comment]
Thanks for the heads up! It looks like the main issue was an outer `while` loop wrapping the shell, preventing it from exiting. ctrl-d should work as of version 5.6.0.

To answer your question, it wasn't intentional. The `nb shell` subcommand isn't actually explicitly handling the signal (aside from a general exit trap at the program level). The shell runs in [a `while read` loop](https://github.com/xwmx/nb/blob/master/nb#L10051).

I hope this helps, and thanks for the words of encouragement!
