### ISSUE TITLE
`nb import *.txt` only importing a single file.

### ISSUE THREAD

**Issue by kitplummer** [xwmx/nb#55]
Am I reading the docs wrong...can `nb import` import multiple files at once?

**Comment by xwmx** [comment]
Yes, it should be working. There's [a passing test here](https://github.com/xwmx/nb/blob/master/test/import.bats#L249) that copies multiple *.md files without copying the other contents of the directory. The preceding `./` in the test is because of [SC2035](https://github.com/koalaman/shellcheck/wiki/SC2035), but I just ran it with with just `import *.md` and it passed on macOS. I also fiddled with the test to make sure it's operating properly and it seems to be, e.g., changing it to `import *` imports the entire contents of the fixture directory.

You can try specifying multiple filenames directory, which is how globbing works internally. There's [also a passing test for multiple filenames](https://github.com/xwmx/nb/blob/master/test/import.bats#L314) so that should work.

It could be that [`noglob`](https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_06.html) [more](https://stackoverflow.com/questions/12225245/set-o-noglob-in-bash-shell-script) is set in your environment, though when I add that to the test it just errors with file not found, which is different from what you are encountering.

**Comment by xwmx** [comment]
Oh, you might need to update to the latest version, since that functionality was only added in the last week or so.

**Comment by kitplummer** [comment]
That was it, just needed to upgrade via brew.  Sorry man.

**Comment by xwmx** [comment]
Awesome!
