### ISSUE TITLE
Notes preview or excerpt doesn't work

### ISSUE THREAD

**Issue by devforfu** [xwmx/nb#71]
Hi there,

I've installed `nb` on Ubuntu 20.04 with `zsh` (oh-my-zsh enabled) and `powerlevel10k` theme. I set up `vim` as notes editor. For some reason, `nb ls -e` and `nb show <id>` commands don't seem to work properly. 

For example, the `--excerpt` key shows only the first line no matter how many lines were requested. The `show` command doesn't show a note, but empty `less` interface without any content.

Did anybody notice the same behavior? Is there any method to debug this?

Thank you!

**Comment by xwmx** [comment]
I'm not sure what would cause that yet, and I haven't found a way to reproduce the issue.

One thing that is common to both operations is that the content is passed through [the highlighting function](https://github.com/xwmx/nb/blob/5.7.8/nb#L1982), so it could potentially be due to a problem with the command being used for highlighting, which is either `bat`, `highlight`, or `pygmentize`. I experimented and haven't been able to reproduce the issue described yet, so I don't know.

Does `--excerpt` display properly without color when the `--no-color` option is used? For example, this command, this command should display 5 items with excerpts 5 lines long and no color: `nb list --excerpt 5 --no-color --limit 5`

**Comment by devforfu** [comment]
@xwmx Yes, that was the problem! With `--no-color` option, the both commands work as expected. So I guess I should install one of these highlighting tools to enable proper colored preview of the notes.
