### ISSUE TITLE
modifying timestamps

### ISSUE THREAD

**Issue by facilitas** [xwmx/nb#95]
Is it possible to modify "added" and "last modified" dates of notes by a script? The documentation does not mention how to manually change them. I have notes to import to nb, with their metadata including time of creation and update recorded in json files.

**Comment by xwmx** [comment]
Hi @facilitas, the timestamps in the current implementation are derived from [`git log`](https://git-scm.com/docs/git-log), with `—added` displaying the datetime of the first commit containing the file and `—updated` displaying the datetime of the last commit in which the file was modified. The date used by `nb` is the [git "author date"](https://alexpeattie.com/blog/working-with-dates-in-git/). There is also a "committer date" that `nb` doesn't use.

[`git commit`](https://git-scm.com/docs/git-commit) includes a `—date` option that can be used to set the author date for a commit to an arbitrary date. It seems like this could be used to record timestamps in git. A script could theoretically be written to iterate over each file, read each timestamp from the json file, then add the file with `git commit --date <added-at>` and then make a change (maybe just change the file permissions?) then make another `git commit --date <updated-at>` with the file. I think it would be a really interesting thing to try.

Personally, a while ago when I imported a few thousand notes with timestamps into `nb` from database-driven apps I saved the timestamps with other metadata fields as [YAML front matter](https://jekyllrb.com/docs/front-matter/). I like front matter because it’s a standard, accessible, and future-proof approach for saving metadata in plain text documents that’s well supported in tools for working with markdown. `nb` has some initial support for front matter, extracting the title fields for listing, filtering, and selecting items. If I was doing it today I'd probably try to see if the `git commit --date` approach works.

I plan on exploring metadata more in this project and have a variety of ideas around this. I hope this helps!

**Comment by facilitas** [comment]
Thanks for the reply. I may put the timestamps in YAML front matter.

**Comment by chmac** [comment]
@xwmx Putting the dates into frontmatter makes a lot of sense.

Would it be crazy to add a date flag that gets passed through to git's `--date` argument?

Maybe I'm being overly anal here, I was thinking about writing a script to achieve this just so I can preserve my dates and see them inside of my `nb` output. But as I say, maybe this is perfectionism at work, and the frontmatter option is definitely a "good enough" approach.

I guess I won't add dates to the frontmatter for new notes going forward, as that would be a manual process. Although I could also write a script to add a `date` field to the frontmatter by reading the `nb` output! Maybe I'm getting carried away... 😆 🔫

**Comment by matthewblott** [comment]
Are there any further thoughts on implementing front matter? I had a look at how [notable](https://github.com/notable/notable) does it, it has the following at the top of the file:

```
---
tags: [tag1, tag2]
title: title
created: '2021-12-10T23:55:31.088Z'
modified: '2021-12-10T23:55:57.651Z'
---

# title

one two buckle shoe

****
```

I've been playing around with `nb` and [adding my own extensions](https://gist.github.com/matthewblott/6ec7fed0ec2d262637f65e92145cba17) and I'd really like to separate metadata from the file's content, particularly tags. I'm going to have a go at doing something like the above for my own needs, let me know if anyone has any ideas. I don't want to duplicate any current work going on :-)
